name: language-conf
version: '0.2.2.0'
synopsis: Conf parsers and pretty-printers for the Haskell programming language.
description: ! '@language-conf@ contains @.conf@ (e.g. nginx configuration)
  parsers and pretty-printers for the Haskell programming language.

  "Data.Conf" exports all the API surface in the package.
'
category: Data
author: Pedro Tacla Yamada
maintainer: tacla.yamada@gmail.com
copyright: Copyright (c) 2016 Pedro Tacla Yamada
license: MIT
github: beijaflor-io/haskell-language-conf
extra-source-files: ./*.conf

flags:
  fromconf:
    description: Build the fromconf utility
    manual: false
    default: false

  toconf:
    description: Build the toconf utility
    manual: false
    default: false

library:
  source-dirs: src
  exposed-modules:
  - Data.Conf
  - Data.Conf.PrettyPrint
  - Data.Conf.Types
  - Data.Conf.Internal
  - Data.Conf.Aeson
  other-modules: []
  dependencies:
  - base >=4.8 && <5
  - deepseq
  - directory >=1.2.2.0
  - filepath >=1.4.0.0
  - megaparsec >=5
  - pretty
  - scientific >=0.3.4.6
  - semigroups >=0.18.1
  - text >=1.2.2.1
  - unordered-containers
  - vector
  - aeson

executables:
  fromconf:
    main: FromConf.hs
    source-dirs: bin
    dependencies:
    - base
    - language-conf
    - text
    - bytestring
    - megaparsec
    - filepath
    - aeson
    - yaml
    when:
    - condition: ! '!(flag(fromconf))'
      buildable: false

  toconf:
    main: ToConf.hs
    source-dirs: bin
    dependencies:
    - base
    - language-conf
    - text
    - bytestring
    - megaparsec
    - filepath
    - aeson
    - yaml
    when:
    - condition: ! '!(flag(toconf))'
      buildable: false

tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - QuickCheck
    - base
    - directory
    - filepath
    - hspec
    - language-conf
    - megaparsec
    - hspec-megaparsec
    - pretty
    - semigroups >=0.18.1
    - text
    - aeson
    - transformers >=0.4.2.0
