name: conffmt
version: '0.2.2.0'
synopsis: A .conf file formatter
description: ! '
  "conffmt" is a @.conf@ file formatter that serves as an example of
  @language-conf@
'
category: Data
author: Pedro Tacla Yamada
maintainer: tacla.yamada@gmail.com
copyright: Copyright (c) 2016 Pedro Tacla Yamada
license: MIT
github: beijaflor-io/haskell-language-conf

executables:
  conffmt:
    main: ConfFmt.hs
    source-dirs: bin
    dependencies:
    - base
    - text
    - optparse-applicative
    - megaparsec
    - language-conf
    - pretty
